#!/bin/bash

procs=$(grep 'int.timing_test' ubench-linux_native.out | grep RES | sed 's/.*n=//g;s/ .*$//g' | sort -n | uniq)
bars='';
for p in $procs; do
bars="$bars $p:int.timing_test.*n=$p.i="
done
#echo $bars
plotubench timing_test 'ebbrt:ubench-ebbrt.out linuxN:ubench-linux_native.out' "$bars"
