#!/bin/bash

plotubench ebb-UP 'ebbrt:ubench-ebbrt.out linuxN:ubench-linux_native.out linuxVM:ubench-linux_VM.out' 'Global:int.GlobalEbbCtrTest.*-.[idv] Heap:int.HeapEbbCtrTest.*-.[idv] HeapCreate:int.HeapEbbCtrTest.*Create HeapDestroy:int.HeapEbbCtrTest.*destroy' 
