#!/bin/bash
#set -x
# To use this you must run the ubench application and save its output to files
# eg.  ubench -c > ubench-linux_native.out; ubench -B -c > ebbrt.out

plotubench cpp 'ebbrt:ubench-ebbrt.out linuxN:ubench-linux_native.out' 'global:int.GlobalCtrTest stack:int.StackCtrTest heap:int.HeapCtrTest.*-.[idv] heapNew:int.HeapCtrTest.*new heapDelete:int.HeapCtrTest.*delete' 
plotubench virtcpp 'ebbrt:ubench-ebbrt.out linuxN:ubench-linux_native.out' 'virtGlobal:int.VirtualGlobalCtrTest virtHeap:int.VirtualHeapCtrTest.*-.[idv] heapNew:int.VirtualHeapCtrTest.*new heapDelete:int.VirtualHeapCtrTest.*delete' 

plotubench ebb-UP 'ebbrt:ubench-ebbrt.out linuxN:ubench-linux_native.out' 'Global:int.GlobalEbbCtrTest.*-.[idv] Heap:int.HeapEbbCtrTest.*-.[idv] HeapCreate:int.HeapEbbCtrTest.*Create HeapDestroy:int.HeapEbbCtrTest.*destroy' 

