#!/bin/bash
#set -x
# To use this you must run the ubench application and save its output to files
# eg.  ubench -c > linux_native.out; ubench -B -c > ebbrt.out

SESADATA_PATH=/opt/sesa-data/scripts
export PATH=$PATH:$SESADATA_PATH

exp=$1
files="$2"
REGEXS="$3"

if [[ -z $exp || -z $files ]]; then
  echo "USAGE: $0 <exp name> <label:file label:file ..> [label:regex label:regex ...]"
  exit -1
fi

if [[ -z $REGEXS ]];then
  REGEXS='data:^.*$'
fi

echo -n > $exp.info 

for re in $REGEXS
do 
    l2=${re%%:*}
    re=${re#*:}
    echo -n "$l2 "
    for f in $files
    do
	l1=${f%%:*}
	f=${f#*:}
	data=$(grep RES  $f | grep $re | sed 's/^.* //g' |  TERSE=1 mmavg)
	echo -n "$l1 $data "
	echo "# $l1 $l2 " >> $exp.info
	grep RES  $f | grep $re | sed 's/^/#/' >> $exp.info
	grep RES  $f | grep $re | sed 's/^.* //g' |  mmavg | sed 's/^/#/' >>$exp.info
    done
    echo 
done > $exp.data 

cat >$exp.gnuplot <<EOF
set boxwidth 1.0 absolute
set style fill   solid 1.00 border lt -1
set key inside right top vertical Right noreverse noenhanced autotitles nobox
set style histogram errorbars linewidth 1
set datafile missing '-'
set style data histograms
set xtics border in scale 0,0 nomirror rotate by -45  offset character 0, 0, 0 autojustify
set xtics  norangelimit font ",8"
set xtics   ()
set title "$exp"
set yrange [0<*:]
set key top left
plot for [i=2:10:7] '$exp.data' using i+3:i+1:i+2:xticlabels(1) t ""
EOF

i=1
for f in $files
do
    l1=${f%%:*}
    f=${f#*:}
    echo "replot NaN title '$l1' lt $i lw 10"
    (( i++ ))
done >> $exp.gnuplot
cat >> $exp.gnuplot <<EOF
set terminal pdfcairo 
set output '${exp}_plot.pdf'
replot
EOF
gnuplot $exp.gnuplot
